name: Build

on:
  push:
    branches: [ "main", "release/**" ]
    paths-ignore: [ ".github/**" ]
  pull_request:
    branches: [ "main", "release/**" ]
    paths-ignore: [ ".github/**" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ github.head_ref || github.ref }}
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        uv sync

    - name: Lint with mypy
      run: |
        uv run task lint

    - name: Test with Python
      shell: bash
      run: |
        uv run task test

    - name: Publish test report
      uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5.5.1
      with:
        commit: ${{ github.head_ref || github.ref }}
        fail_on_failure: true
        include_passed: false
        detailed_summary: true
        include_time_in_summary: true
        check_name: |
          Test Report (${{ matrix.python-version }})
        report_paths: |
          **/results.xml

    - name: Upload coverage to Codecov
      if: github.event_name == 'push'
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
      with:
        files: ./coverage.xml
        env_vars: OS,PYTHON
        name: codecov-umbrella
